spring.application.name=EnterpriseAuditing

spring.mongodb.uri=mongodb://root:secret@localhost:27017/auditdb?authSource=admin
spring.docker.compose.enabled=false

# SQS
aws.sqs.audit-queue-url=https://sqs.ap-south-1.amazonaws.com/149511939808/enterprise-audit-events
aws.sqs.audit-queue-name=enterprise-audit-events
spring.cloud.aws.region.static=ap-south-1

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#JWT
security.jwt.secret=change-this-to-a-long-random-secret-key-at-least-32-characters
security.jwt.expiration=3600000