spring.application.name=EnterpriseAuditing

spring.data.mongodb.uri=mongodb://root:secret@localhost:27017/auditdb?authSource=admin
spring.docker.compose.enabled=false

# SQS
aws.sqs.audit-queue-url=https://sqs.ap-south-1.amazonaws.com/149511939808/enterprise-audit-events
aws.sqs.audit-queue-name=enterprise-audit-events
spring.cloud.aws.region.static=ap-south-1

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#JWT
security.jwt.secret=change-this-to-a-long-random-secret-key-at-least-32-characters
security.jwt.expiration=3600000

# Spring Boot Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized

# CloudWatch Metrics
management.cloudwatch.metrics.export.enabled=true
management.cloudwatch.metrics.export.namespace=EnterpriseAuditing
management.cloudwatch.metrics.export.step=1m